services:
  - type: web
    name: fasting-forecast
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/database
      sizeGB: 1